# https://hub.docker.com/_/node/
FROM node:20-alpine as base

WORKDIR /home/node/app

# used solely for unit testing
RUN sudo apt-get install build-essential \
  libcairo2-dev libpango1.0-dev libjpeg-dev \
  libgif-dev librsvg2-dev

FROM base as install

COPY ./package.json     /home/node/app
COPY ./package-lock.json /home/node/app
RUN chown node:node /home/node/app

# USER node
RUN npm install

FROM install as run

COPY . /home/node/app

EXPOSE 3333
VOLUME /home/node/app/src

CMD npm run dev

