# https://hub.docker.com/_/node/
FROM node:20-alpine as base

WORKDIR /home/node/app

RUN apk update

# Install build-base (Alpine's equivalent of build-essential)
RUN apk add build-base

# Install other dependencies
RUN apk add \
  cairo-dev \
  pango-dev \
  jpeg-dev \
  librsvg-dev
# gif-dev \

FROM base as install

COPY ./package.json     /home/node/app
COPY ./package-lock.json /home/node/app
RUN chown node:node /home/node/app

# USER node
RUN npm install

FROM install as run

COPY . /home/node/app

EXPOSE 3333
VOLUME /home/node/app/src

CMD npm run dev

