version: "3.8"

services:
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   env_file: .env
  #   networks:
  #     - skynet
  #   ports:
  #     - "5555"
  #   # volumes:
  frontend:
    build:
      # target: development
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file: .env
    environment:
      - NODE_ENV=development
    ports:
      - "3333"
      # - "9229"
    networks:
      - skynet
    volumes:
      - ./frontend/src/:/home/node/app/src/
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      # - backend
      - frontend
    ports:
      - "80:80"
      # - "9229:9229" # Enable profiling
      - "443:443"
    networks:
      - skynet
networks:
  skynet:
    driver: bridge