version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file: .env
    depends_on:
      - database
    networks:
      - skynet
    ports:
      - "3222"
    volumes:
      - ./backend/src/:/home/node/app/src/
  frontend:
    build:
      # target: development
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file: .env
    environment:
      - NODE_ENV=development
    ports:
      - "3333"
      - "9229:9229" # debugging
    networks:
      - skynet
    volumes:
      - ./frontend/src/:/home/node/app/src/
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      # - "9229:9229" # Enable profiling
      - "443:443"
    networks:
      - skynet
  database:
    image: postgres:15-alpine
    restart: unless-stopped
    networks:
      - skynet
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
networks:
  skynet:
    driver: bridge